export const SAVE_PERSONAL_INFORMATION_REQUEST = 'SAVE_PERSONAL_INFORMATION_REQUEST';
export const SAVE_PERSONAL_INFORMATION_SUCCESS = 'SAVE_PERSONAL_INFORMATION_SUCCESS';
export const SAVE_PERSONAL_INFORMATION_FAILURE = 'SAVE_PERSONAL_INFORMATION_FAILURE';